In [101]:
import numpy as np

# Fixed input: Erste Zeile ist der Draw, danach n Spielbretter der Größe 5x5
def read_bingo(input_):
    with open(input_, "r") as f:
        cont = f.readlines()
        
    draw = np.array(cont[0].split(","), dtype=int)
    i=2
    boards = []
    while i < len(cont):
        boards.append(np.matrix(np.loadtxt(input_, skiprows=i, max_rows=5)))
        i+=6

    return draw, np.array(boards)

def check_win(board):
    #Vertikal oder Horizontal
    i = 0
    while not (np.where(board[i,:] == -1)[-1].size == 5 \
              or np.where(board[:,i] == -1)[-1].size == 5 \
              or np.where(board[:,i] == -1)[-1].size == 5):
        i += 1
        if i == 5: break
    else:
        return True
        
    # Diagonal
    a = np.where(np.array([boards[0][i,i] for i in range(5)]) == -1)[0].size == 5
    b = np.where(np.array([boards[0][4-i,i] for i in range(5)]) == -1)[0].size == 5
    return a or b

def calc_result(board, number):
    print("Result: ", int(np.sum(board[board != -1])*number))
    
draw, boards = read_bingo("input.txt")
won = False
for number in draw:
    for i in range(len(boards)):
        boards[i][np.where(boards[i] == number)] = -1
        won = check_win(boards[i])
        if won:
            calc_result(boards[i], number)
            break
    if won: break


Result:  87456


In [157]:
draw, boards = read_bingo("input.txt")
won = False
active_boards = np.ones(len(boards), dtype=int)
for number in draw:
    for i in range(len(boards)):
        boards[i][np.where(boards[i] == number)] = -1
        won = check_win(boards[i]) and active_boards[i] == 1
        if won and np.sum(active_boards) > 1: 
            active_boards[i] = 0
        elif won and np.sum(active_boards) == 1:
            calc_result(boards[active_boards==True], number)
            break
    if won and np.sum(active_boards) == 1: break

[[[46. -1. -1. 86. -1.]
  [-1. -1. -1. -1. 53.]
  [-1. -1. -1. -1. -1.]
  [-1. 95. -1. -1. -1.]
  [28. -1. 91. -1. -1.]]] 39
Result:  15561
