In [1]:
import numpy as np

class DAY_09:
    def __init__(self, vent_file, verbose=True):
        self.__vent_file = vent_file
        self.__verbose = verbose
        
    def read_file(self):
        vents_from_file = []
        with open(self.__vent_file, "r") as f:
            cont = f.readlines()
            for line in cont:
                vents_line = []
                for i in line:
                    try:#Ignoriere Zeilenumbruch
                        vents_line.append(int(i))
                    except ValueError:
                        continue
                vents_from_file.append(np.array(vents_line))
        vents_from_file = np.array(vents_from_file)
        
        #Erstelle eine größere Matrix in welcher jeder Eintrag 10 ist. Wähle 10, weil das Maximum des
        #Inputs den Wert 9 hat. In diese Matrix wird der Puzzle-Input gelesen. Dadurch müssen keine
        #Listengrenzen bei der Suche nach dem kleinsten Element berücksichtigt werden.
        y_len = len(vents_from_file)
        x_len = len(vents_from_file[0])
        self.__helper_matrix = 10 * np.ones((y_len+4,x_len+4))
        for i in range(2,y_len+2):
            for j in range(2,x_len+2):
                self.__helper_matrix[i,j] = vents_from_file[i-2,j-2]
        if self.__verbose: print(self.__helper_matrix)
        self.__basin = np.array(self.__helper_matrix) * 0
        
    #Aufgabe 1
    def find_smallest_elements(self):
        self.__smallest = []
        self.__lowpoints = []
        y_len = len(self.__helper_matrix)
        x_len = len(self.__helper_matrix[0])
        for i in range(2, y_len-2):
            for j in range(2, x_len-2):
                surrounding = np.array([self.__helper_matrix[i-1, j], self.__helper_matrix[i+1, j], \
                               self.__helper_matrix[i, j+1], self.__helper_matrix[i, j-1]])
                if np.where(surrounding > self.__helper_matrix[i,j])[0].size == 4:
                    self.__smallest.append(self.__helper_matrix[i,j]+1)
                    self.__lowpoints.append([i,j])
                    if self.__verbose: print(self.__helper_matrix[i,j], surrounding)
        return self.__lowpoints
                        
    #Aufgabe 2
    def in_basin(self, x_pos=0, y_pos=0):
        #Teste ob ein Nachbar 9 oder 10 ist (10 ist die Umrandung, welche Listenüberläufe verhindern soll)
        #und ob das Feld schon gezählt wurde. Wenn nein, rufe die Methode erneut auf mit 
        #Wenn ein Nachbar um 1 größer ist, erhöhe einen Zähler und rufe die Methode erneut auf. Setze ein
        #Flag, dass dieses Feld bereits gezählt ist.
        if self.__basin[x_pos+1, y_pos] != 1 and self.__helper_matrix[x_pos+1,y_pos] < 9:
            self.__basin[x_pos, y_pos] = 1
            self.in_basin(x_pos+1, y_pos)
            self.__basin[x_pos+1, y_pos] = 1
        if self.__basin[x_pos-1, y_pos] != 1 and self.__helper_matrix[x_pos-1,y_pos] < 9:
            self.__basin[x_pos, y_pos] = 1
            self.in_basin(x_pos-1, y_pos)
            self.__basin[x_pos-1, y_pos] = 1                        
        if self.__basin[x_pos, y_pos+1] != 1 and self.__helper_matrix[x_pos,y_pos+1] < 9:
            self.__basin[x_pos, y_pos] = 1
            self.in_basin(x_pos, y_pos+1)
            self.__basin[x_pos, y_pos+1] = 1
        if self.__basin[x_pos, y_pos-1] != 1 and self.__helper_matrix[x_pos,y_pos-1] < 9:
            self.__basin[x_pos, y_pos] = 1
            self.in_basin(x_pos, y_pos-1)
            self.__basin[x_pos, y_pos-1] = 1

    def puzzle_2(self):
        results = []
        for coord in self.__lowpoints:
            #Für jeden Lowpoint, erstelle eine Karte, in welcher die Basins notiert werden
            self.__basin = np.array(self.__helper_matrix) * 0
            self.in_basin(coord[0], coord[1])
            if self.__verbose: print(self.__basin)
            if self.__verbose: print(np.where(self.__basin == 1)[0].size)
            #Füge die Größe des Basins ein
            results.append(np.where(self.__basin == 1)[0].size)
        print(np.product(sorted(results)[-3:]))
        if self.__verbose: print(sorted(results))

    def show_results(self):
        print(self.__smallest, int(np.sum(self.__smallest)))
        
day09_test_1 = DAY_09("example.txt")
day09_test_1.read_file()
day09_test_1.find_smallest_elements()
day09_test_1.show_results()

day09_test_1 = DAY_09("input.txt", False)
day09_test_1.read_file()
day09_test_1.find_smallest_elements()
day09_test_1.show_results()

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10.  2.  1.  9.  9.  9.  4.  3.  2.  1.  0. 10. 10.]
 [10. 10.  3.  9.  8.  7.  8.  9.  4.  9.  2.  1. 10. 10.]
 [10. 10.  9.  8.  5.  6.  7.  8.  9.  8.  9.  2. 10. 10.]
 [10. 10.  8.  7.  6.  7.  8.  9.  6.  7.  8.  9. 10. 10.]
 [10. 10.  9.  8.  9.  9.  9.  6.  5.  6.  7.  8. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
1.0 [10.  9.  9.  2.]
0.0 [10.  1. 10.  1.]
5.0 [8. 6. 6. 8.]
5.0 [ 6. 10.  6.  6.]
[2.0, 1.0, 6.0, 6.0] 15
[1.0, 1.0, 4.0, 5.0, 5.0, 3.0, 1.0, 2.0, 1.0, 1.0, 3.0, 1.0, 1.0, 6.0, 2.0, 6.0, 5.0, 3.0, 3.0, 2.0, 6.0, 1.0, 1.0, 1.0, 1.0, 2.0, 5.0, 3.0, 2.0, 4.0, 1.0, 4.0, 2.0, 1.0, 4.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 5.0, 2.0, 1.0, 5.0, 1.0, 2.0, 1.0, 2.0, 3.0, 2.0, 2.0, 1.0, 5.0, 1.0, 1.0, 3.0, 3.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 5.0, 1.0, 2.0, 1.0, 4.0, 2.0, 4.0, 2.0,

In [2]:
day09_test_2 = DAY_09("example.txt")
day09_test_2.read_file()
day09_test_2.find_smallest_elements()
day09_test_2.puzzle_2()

day09_puzzle_2 = DAY_09("input.txt", False)
day09_puzzle_2.read_file()
day09_puzzle_2.find_smallest_elements()
day09_puzzle_2.puzzle_2()

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10.  2.  1.  9.  9.  9.  4.  3.  2.  1.  0. 10. 10.]
 [10. 10.  3.  9.  8.  7.  8.  9.  4.  9.  2.  1. 10. 10.]
 [10. 10.  9.  8.  5.  6.  7.  8.  9.  8.  9.  2. 10. 10.]
 [10. 10.  8.  7.  6.  7.  8.  9.  6.  7.  8.  9. 10. 10.]
 [10. 10.  9.  8.  9.  9.  9.  6.  5.  6.  7.  8. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
1.0 [10.  9.  9.  2.]
0.0 [10.  1. 10.  1.]
5.0 [8. 6. 6. 8.]
5.0 [ 6. 10.  6.  6.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0