In [1]:
import numpy as np


class DAY_15:
    def __init__(self, fname, verbose=True, size=10):
        self.__fname = fname
        self.__verbose = verbose
        self.__size = size
        self.__q = []#Alle besuchbaren Punkte
        self.__q_val = []
        
    def read_input(self):
        self.__cavern_map = np.ones((self.__size, self.__size))
        cavern = np.loadtxt(self.__fname, dtype=str)
        for x in range(self.__size):
            for y in range(self.__size):
                self.__cavern_map[x,y] = int(cavern[x][y])

        if self.__verbose: print(self.__cavern_map)
        self.__cavern_map[0,0] = 0
        self.__q.append([1,0])
        self.__q.append([0,1])
        self.__q_val.append(self.__cavern_map[self.__q[0][0], self.__q[0][1]])
        self.__q_val.append(self.__cavern_map[self.__q[1][0], self.__q[1][1]])
        self.__not_visited = -1*np.ones((self.__size, self.__size))
        self.__not_visited[0,0] = 1
        
    def next_node(self):
        print(self.__q_val)
        for i in range(self.__size**2+1):
            #Suche den Punkt, welcher am günstigsten zu erreichen ist
            min_q_val = np.min(self.__q_val)
            index_of_min_q = self.__q_val.index(min_q_val)#Problem wenn der kleinste Index häufiger auftritt?
            index_of_next_node = self.__q[index_of_min_q]


            #Entferne den gefundenen Punkt aus der Q-Liste
            popped_q = self.__q.pop(index_of_min_q)
            popped_q_val = self.__q_val.pop(index_of_min_q)
                
            #Teste ob dieser Punkt das Ziel ist
            if index_of_next_node[0] == self.__size-1 and index_of_next_node[1] == self.__size-1: 
                print("finished", popped_q_val)
                break

            #Füge die neuen Elemente ein
            #if i > (self.__size-1)**2: print(i, min_q_val)
            if index_of_next_node[0]+1 < self.__size and self.__not_visited[index_of_next_node[0]+1,index_of_next_node[1]] == -1:
                self.__q.append([index_of_next_node[0]+1,index_of_next_node[1]])
                self.__q_val.append(min_q_val + self.__cavern_map[index_of_next_node[0]+1,index_of_next_node[1]])
                self.__not_visited[index_of_next_node[0]+1,index_of_next_node[1]] = 1
                
            if index_of_next_node[0]-1 >= 0 and self.__not_visited[index_of_next_node[0]-1,index_of_next_node[1]] == -1:
                self.__q.append([index_of_next_node[0]-1,index_of_next_node[1]])
                self.__q_val.append(min_q_val + self.__cavern_map[index_of_next_node[0]-1,index_of_next_node[1]])
                self.__not_visited[index_of_next_node[0]-1,index_of_next_node[1]] = 1

            if index_of_next_node[1]+1 < self.__size and self.__not_visited[index_of_next_node[0],index_of_next_node[1]+1] == -1:
                self.__q.append([index_of_next_node[0],index_of_next_node[1]+1])
                self.__q_val.append(min_q_val + self.__cavern_map[index_of_next_node[0],index_of_next_node[1]+1])
                self.__not_visited[index_of_next_node[0],index_of_next_node[1]+1] = 1

            if index_of_next_node[1]-1 >= 0 and self.__not_visited[index_of_next_node[0],index_of_next_node[1]-1] == -1:
                self.__q.append([index_of_next_node[0],index_of_next_node[1]-1])
                self.__q_val.append(min_q_val + self.__cavern_map[index_of_next_node[0],index_of_next_node[1]-1]) 
                self.__not_visited[index_of_next_node[0],index_of_next_node[1]-1] = 1

           
        print(index_of_next_node, i, min_q_val)
        
day15_test_1 = DAY_15("example.txt", True, 10)
day15_test_1.read_input()
day15_test_1.next_node()

import datetime as dt
start_time = dt.datetime.now()
day15_puzzle_1 = DAY_15("input.txt", size=100)
day15_puzzle_1.read_input()
day15_puzzle_1.next_node()
print((dt.datetime.now()-start_time).total_seconds())

[[1. 1. 6. 3. 7. 5. 1. 7. 4. 2.]
 [1. 3. 8. 1. 3. 7. 3. 6. 7. 2.]
 [2. 1. 3. 6. 5. 1. 1. 3. 2. 8.]
 [3. 6. 9. 4. 9. 3. 1. 5. 6. 9.]
 [7. 4. 6. 3. 4. 1. 7. 1. 1. 1.]
 [1. 3. 1. 9. 1. 2. 8. 1. 3. 7.]
 [1. 3. 5. 9. 9. 1. 2. 4. 2. 1.]
 [3. 1. 2. 5. 4. 2. 1. 6. 3. 9.]
 [1. 2. 9. 3. 1. 3. 8. 5. 2. 1.]
 [2. 3. 1. 1. 9. 4. 4. 5. 8. 1.]]
[1.0, 1.0]
finished 40.0
[9, 9] 97 40.0
[[7. 4. 6. ... 8. 1. 9.]
 [1. 7. 9. ... 2. 3. 9.]
 [9. 4. 8. ... 6. 4. 9.]
 ...
 [6. 9. 8. ... 1. 7. 9.]
 [9. 9. 9. ... 9. 1. 9.]
 [2. 7. 9. ... 7. 1. 9.]]
[1.0, 4.0]
finished 621.0
[99, 99] 10000 621.0
0.15959


In [2]:
cavern = np.ones((500, 500))
cavern_short = np.ones((100, 100))
with open("input.txt", "r") as f:
    content = f.readlines()
    for i in range(100):
        for j in range(100):
            cavern[i,j] = int(content[i][j])
            cavern_short[i,j] = int(content[i][j])
            for k in range(5):
                for l in range(5):
                    cavern[i+k*100, j+l*100] = int(content[i][j])+(k+l) if int(content[i][j])+(k+l) <= 9 else int(content[i][j])+(k+l)-9
print(cavern[0, 10])
print(cavern[0, 110])
print(cavern[0, 210])
print(cavern[0, 310])
print(cavern[0, 410])
print()
print(cavern[1, 10])
print(cavern[1, 110])
print(cavern[1, 210])
print(cavern[1, 310])
print(cavern[1, 410])
print()
print(cavern[2, 10])
print(cavern[2, 110])
print(cavern[2, 210])
print(cavern[2, 310])
print(cavern[2, 410])
print()
print(cavern[3, 10])
print(cavern[3, 110])
print(cavern[3, 210])
print(cavern[3, 310])
print(cavern[3, 410])
print()
print(cavern[4, 10], cavern[104, 10], cavern[204, 10])
print(cavern[4, 110], cavern[104, 110], cavern[204, 110])
print(cavern[4, 210], cavern[104, 210], cavern[204, 210])
print(cavern[4, 310], cavern[104, 310], cavern[204, 310])
print(cavern[4, 410], cavern[104, 410], cavern[204, 410])

np.savetxt("input_2.txt", cavern, delimiter="", fmt="%d")

1.0
2.0
3.0
4.0
5.0

9.0
1.0
2.0
3.0
4.0

9.0
1.0
2.0
3.0
4.0

8.0
9.0
1.0
2.0
3.0

6.0 7.0 8.0
7.0 8.0 9.0
8.0 9.0 1.0
9.0 1.0 2.0
1.0 2.0 3.0


In [3]:
day15_test_2 = DAY_15("example_2.txt", True, 50)
day15_test_2.read_input()
day15_test_2.next_node()

import datetime as dt
start_time = dt.datetime.now()
day15_puzzle_1 = DAY_15("input_2.txt", size=500)
day15_puzzle_1.read_input()
day15_puzzle_1.next_node()
print((dt.datetime.now()-start_time).total_seconds())

[[1. 1. 6. ... 2. 8. 6.]
 [1. 3. 8. ... 1. 2. 6.]
 [2. 1. 3. ... 7. 6. 3.]
 ...
 [7. 5. 6. ... 5. 2. 8.]
 [5. 6. 4. ... 4. 1. 9.]
 [6. 7. 5. ... 4. 7. 9.]]
[1.0, 1.0]
finished 315.0
[49, 49] 2500 315.0
[[7. 4. 6. ... 3. 5. 4.]
 [1. 7. 9. ... 6. 7. 4.]
 [9. 4. 8. ... 1. 8. 4.]
 ...
 [1. 4. 3. ... 9. 6. 8.]
 [4. 4. 4. ... 8. 9. 8.]
 [6. 2. 4. ... 6. 9. 8.]]
[1.0, 4.0]
finished 2904.0
[499, 499] 250000 2904.0
11.580721
